### ISSUE TITLE
MobileNet & InceptionNetV3 models

### ISSUE THREAD

**Issue by ahmdtaha** [junsukchoe/ADL#7]
Thank you for providing the tf implementation.

You shared the code for the VGG and ResNet models, can you please share the mobileNet and InceptionNetV3 models ? 

A code snippet, or a gist, would be fine. No need to integrate it with the current released code base

Thanks again

**Comment by batrlatom** [comment]
I would love to see densenet_ADL too!

**Comment by junsukchoe** [comment]
Different from VGG and ResNet codes, the MobileNet V1 and Inception V3 codes are written based on tf.slim official codes. I am not used to tf.slim, so my codes are really hard to read right now (even for me!). So I have to clean up the codes before releasing it, but unfortunately I have no resources to do it right now. However I will release the codes in November this year at the latest. 

Sorry for your inconvenience.
